Add `PatriciaMap::iter_prefix_mut` and `Node::iter_mut` functions
sile/patricia_tree pull request #13
Opened 2021-07-06 10:15 UTC by jaxrtech

Hello!

I was using the `patricia_tree` library and ran into issue that there was no `mut` version of the `iter_prefix` function. I've went on and implemented it and added a simple unit test to ensure that it iterates and you're able to mutable values.

Let me know if this looks good! Glad to help.

2021-07-07 00:37 UTC, sile commented
Thank you for your contribution!
Let me review this PR this weekend.

2021-07-11 11:42 UTC, sile requested changes
This PR basically seems good, but I left some comments about naming conventions. Please take a look when you have time.

Besides, since the lint CI failed due to formatting errors, please execute `cargo fmt` to format the code.

2021-07-11 11:42 UTC, sile commented on src/node.rs
> +    pub fn take_value_mut(self) -> Option<&'a mut V> {
IMO, the current name seems a bit confusing because it doesn't actually take ownership of the value (i.e., the value will not be removed from the node after calling this method).
So how about renaming it as follows?
```suggestion
    pub fn into_value_mut(self) -> Option<&'a mut V> {
```

2021-07-11 11:42 UTC, sile commented on src/node.rs
> +pub struct NodeMutRef<'a, V: 'a> {
IMO, we can remove the `Ref` suffix from the class name.
```suggestion
pub struct NodeMut<'a, V: 'a> {
```

2021-07-11 11:42 UTC, sile commented on src/node.rs
> +pub(crate) struct NodeProxyMut<'a, V> {
The word "Proxy" in the class name sounds not intuitive to me.
And I'm wondering if the class could be merged with `NodeMutRef` by adding `sibling` and `child` to the class as follows:
```Rust
pub struct NodeMutRef<'a, V: 'a> {
    label: &'a [u8],
    sibling: Option<&'a mut Node<V>>,
    child: Option<&'a mut Node<V>>,
    value: Option<&'a mut V>,
}
```

Then, the `IterMut::next()` implementation could be,
```rust
impl<'a, V: 'a> Iterator for IterMut<'a, V> {
    type Item = (usize, NodeMutRef<'a, V>);
    fn next(&mut self) -> Option<Self::Item> {
        if let Some((level, node)) = self.stack.pop() {
            let mut node = node.proxy_mut(); // TODO: Rename the method with, e.g., `as_mut()`
            if level != 0 {
                if let Some(sibling) = node.sibling.take() {
                    self.stack.push((level, sibling));
                }
            }
            if let Some(child) = node.child.take() {
                self.stack.push((level + 1, child));
            }
            Some((level, node))
        } else {
            None
        }
    }
}
```

What do you think of that?

2021-07-11 14:03 UTC, jaxrtech commented on src/node.rs
> +    pub fn take_value_mut(self) -> Option<&'a mut V> {
Gotcha, that makes sense why it's better to just name it `into_*`. I've renamed the function.

2021-07-11 14:03 UTC, jaxrtech commented on src/node.rs
> +pub struct NodeMutRef<'a, V: 'a> {
I've done so 👍🏾

2021-07-11 14:05 UTC, jaxrtech commented on src/node.rs
> +pub(crate) struct NodeProxyMut<'a, V> {
Nice suggestion! I've merged the two structs together so now there is just one. I forgot about using `Option::take(&mut self)` to just move the reference out of the option without having to own the `Option`. I'll have to use that one more often. Thanks, I've applied those suggestions.

2021-07-11 14:06 UTC, jaxrtech commented
@sile Thanks again for taking a look at my PR. I've remembered to run `cargo fmt` this time haha. Let me know if this looks good now.

2021-07-12 00:17 UTC, sile approved these changes
Thank you for your swift response! LGTM!

Though the CI still failed, it seems due to the clippy version up and not relevant to your changes. I'll fix that after merging this PR.

2021-07-12 00:17 UTC, merged